### PR TITLE
Site:Info example files added

### PR DESCRIPTION
**Pull request by david-oh-git**
i added example code for the API:Siteinfo

### CODE REVIEW

**Comment by srish** [comment]
@david-oh-git Hello David! Could you clarify if you are interested in applying for GSoC or Outreachy w/ Wikimedia? From your contribution activity on commons-app/apps-android-commons, I'm not sure :) I 'm asking as this task is for Outreachy candidates..

**Comment by david-oh-git** [comment]
> @david-oh-git Hello David! Could you clarify if you are interested in applying for GSoC or Outreachy w/ Wikimedia? From your contribution activity on commons-app/apps-android-commons, I'm not sure :) I 'm asking as this task is for Outreachy candidates..

Yes i am. i use a different email to apply.

**Comment by srish** [comment]
> Yes i am. i use a different email to apply.

@david-oh-git which program you are interested in applying to? GSoC or Outreachy?

**Comment by david-oh-git** [comment]
> > Yes i am. i use a different email to apply.
> 
> @david-oh-git which program you are interested in applying to? GSoC or Outreachy?

Outreachy

**Pull request closed without merging**
