### PR TITLE
PHP sample code for token module

### PR DESCRIPTION
**Pull request by Jayprakash-SE**
PHP sample code for token module

### CODE REVIEW

**Comment by Jayprakash-SE** [comment]
To get token from the $result values, we use $result['query']['tokens']['logintoken']

**Comment by Jayprakash-SE** [comment]
> @Jayprakash-SE The file format looks good to me! I've only one small suggestion, consider changing the variable name `$curlHandle` to `$ch`. You can proceed with the next steps from here on.

Done, Consider for merging the pull request :)

**Comment by srish** [comment]
@Jayprakash-SE Cool! Merging it now. In your final pull request on this topic, make sure to show how to obtain token from results like you have mentioned above: `$result['query']['tokens']['logintoken']`

**Comment by Jayprakash-SE** [comment]
> @Jayprakash-SE Cool! Merging it now. In your final pull request on this topic, make sure to show how to obtain token from results like you have mentioned above: `$result['query']['tokens']['logintoken']`

Ok.

**Pull request merged**
