### PR TITLE
Links to mediawikijs code samples from mediawikijs/README.md

### PR DESCRIPTION
**Pull request by zainababubakar**
fix to issue #188

### CODE REVIEW

**Comment by zainababubakar** [comment]
Hi @brendajerop, kindly review

**Comment by brendajerop** [comment]
@zainababubakar Please resolve the merge conflicts. Make sure to rebase your changes on top of this in the upstream's master:)

**Comment by zainababubakar** [comment]
Hi @brendajerop, i've resolved the conflicts

**Comment by brendajerop** [comment]
@zainababubakar Did you rebase?
image

**Comment by zainababubakar** [comment]
Yes @brendajerop i did, I'm really confused as to why there are still conflicts

**Comment by brendajerop** [comment]
@zainababubakar What response do you get when you run `git pull --rebase upstream master`?

**Comment by zainababubakar** [comment]
image
@brendajerop

**Pull request closed without merging**
