### PR TITLE
Added Sample codes for API:Main_module

### PR DESCRIPTION
**Pull request by zaycodes**
Hello @brendajerop, kindly review https://www.mediawiki.org/wiki/User:Zaycodes/Sandbox/API:Main_module

### CODE REVIEW

**Comment by brendajerop** [comment]
@zaycodes Were you able to get a response? I'm not getting any.

**Comment by zaycodes** [comment]
> @zaycodes Were you able to get a response? I'm not getting any.

@brendajerop , yes i was able to get response

**Comment by brendajerop** [comment]
@zaycodes I keep getting this error 
image

**Comment by zaycodes** [comment]
@brendajerop, I'll check it

**Comment by zaycodes** [comment]
@brendajerop, it's fine now, I've fixed it

**Pull request merged**
