### PR TITLE
Add sample code for microTask-3

### PR DESCRIPTION
**Pull request by adarshPatel509**
Added javascript equivalent code for the following python codes.
 parse_wikitable.py
 userrights.py

### CODE REVIEW

**Comment by adarshPatel509** [comment]
@srish please review this. Thanks!

**Comment by srish** [comment]
@adarshPatel509 Thanks for your work on this! It looks you sent a pull request with changes to ~10 files. However, you were only supposed to send for one that you claimed `userrights.py` in https://phabricator.wikimedia.org/T215681. Others are working on other files. It would be great if you could make adjustments to this pull request, remove other files and only keep that you picked.

**Comment by adarshPatel509** [comment]
@srish, I have removed other JS files. Please review this. Thanks!

**Comment by adarshPatel509** [comment]
@srish I have made the requested changes.
I have checked for jshint errors and followed the same code convention as used in other JS files.
Please review this, Thanks.

**Pull request closed without merging**
